#+title: Introduction to programming in Julia
#+slug: julia

{{<i>}}
{{<itxtb "Instructor:" "Marie-Helene Burle (WestGrid)">}}<br>
{{<itxtb "Length:" "2 days">}}<br>
{{<itxtb "Level:" Beginner>}}<br>
{{<itxtb "Prerequisites:" "Experience with a programming language (e.g. R, Python)">}}<br>
{{<itxtb "Goal:" "Introduce you to the Julia programming language">}}<br>
{{<itxt "Program:" "We will meet during the Zoom sessions">}}<br>
{{<itxt " " "You will go over the material in Readings, Videos, and Practices on your own">}}<br>
{{<itxt " " "Going over the self-directed sections prior to our meetings is necessary to be able to follow">}}<br>
{{<itxtb " " " ">}}<br>
{{<itxtb "Time zone:" "Pacific Daylight Time (UTC-07:00)">}}<br>
{{</i>}}

*June 1*
{{<zt "9–9:30am">}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-01-intro.html" text="Introduction to the WestGrid Summer School Julia course">}}<br>
In this session, I will go over the program for this course and we will get to know each other.
{{</zt>}}

{{<reading>}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-02-why.html" text="Why another programming language?">}}
{{</reading>}}

{{<practice>}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-03-install.html" text="Software installation and data download">}}
{{</practice>}}

{{<video>}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-04-repl.html" text="The Julia REPL">}}
{{</video>}}

{{<practice>}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-05-pkg.html" text="Packages">}}
{{</practice>}}

{{<dt "2–3:30pm">}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-06-debug.html" text="Issues installing Julia and Julia packages or downloading the data">}}<br>
This debugging session is not part of the actual course. If you successfully <a href="https://westgrid-julia.netlify.app/summerschool2020/jl-03-install.html">installed the required software and downloaded the data</a> and if you <a href="https://westgrid-julia.netlify.com/summerschool2020/jl-05-pkg.html">installed the required Julia packages</a>, you do not need to attend it.
{{</dt>}}

{{<reading>}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-07-fun.html" text="Functions, control flow, and macros">}}
{{</reading>}}

*June 2*
{{<zt "9–11am">}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-08-var.html" text="Variables and types">}}<br>
In this session, we will write our first Julia script; talk about Julia's syntax, variables and types; data import and export; data frames and indexing; and we will prepare the data to plot in the next session. <em>Please come prepared with your installations and data (on your computer).</em>
{{</zt>}}

{{<practice>}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-09-plots.html" text="Plotting">}}
{{</practice>}}

{{<reading>}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-10-cluster.html" text="Using Julia on Compute Canada clusters">}}
{{</reading>}}

{{<practice>}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-11-multithreading" text="Multi-threading">}}
{{</practice>}}

{{<reading>}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-12-distributed.html" text="Distributed computing">}}
{{</reading>}}

{{<zt "2–3pm">}}
{{<link url="https://westgrid-julia.netlify.app/summerschool2020/jl-13-parallel.html" text="Parallel computing in Julia">}}
{{</zt>}}

{{<external>}}
<u>Documentation:</u>
<br>
<a href="https://julialang.org/">Julia website</a><br>
<a href="https://docs.julialang.org/en/v1/">Julia documentation</a><br>
<a href="https://julialang.org/learning/">Online training material</a><br>
<a href="https://www.youtube.com/user/JuliaLanguage">Julia YouTube channel</a><br>
<a href="https://en.wikibooks.org/wiki/Introducing_Julia">Julia Wikibook</a><br>
<a href="https://www.juliabloggers.com/">Blog aggregator for Julia</a><br>
<br>
<u>Getting help:</u>
<br>
<a href="https://discourse.julialang.org/">Julia Discourse forum</a><br>
<a href="https://stackoverflow.com/tags/julia">[julia] tag on Stack Overflow</a><br>
<a href="https://app.slack.com/client/T68168MUP/C67910KEH">Julia Slack team</a>
(you need to <a href="https://julialang.org/slack/">agree to the community code of conduct</a> first)<br>
<a href="https://twitter.com/search?q=%23julialang">#julialang hashtag on Twitter</a><br>
<a href="https://www.reddit.com/r/Julia/">Julia subreddit</a><br>
<a href="https://gitter.im/JuliaLang/julia">Julia Gitter channel</a><br>
<a href="https://webchat.freenode.net/#julia">#julia IRC channel on Freenode</a><br>
<br>
<u>IDE:</u>
<br>
<a href="https://junolab.org/">Juno</a> (built on <a href="https://atom.io/">Atom</a>)<br>
<a href="https://www.gnu.org/software/emacs/">Emacs</a> with the <a href="https://github.com/JuliaEditorSupport/julia-emacs">julia-emacs</a> and <a href="https://github.com/tpapp/julia-repl">julia-repl</a> packages<br>
<a href="https://www.gnu.org/software/emacs/">Emacs</a> with the <a href="https://github.com/emacs-ess/ESS">ESS</a> package<br>
<a href="https://jupyter.org/">Project Jupyter</a> with the <a href="https://github.com/JuliaLang/IJulia.jl">Julia kernel</a><br>
<a href="https://jupyter.org/">Project Jupyter</a> with the <a href="https://github.com/JuliaLang/IJulia.jl">Julia kernel</a> in <a href="https://www.gnu.org/software/emacs/">Emacs</a> with the <a href="http://millejoh.github.io/emacs-ipython-notebook/">EIN</a> package<br>
{{</external>}}
