#+title: Introduction to ML with PyTorch
#+slug: ml

{{<i>}}
{{<itxtb "Instructor:" "Marie-Helene Burle (WestGrid)">}}<br>
{{<itxtb "Length:" "2 days">}}<br>
{{<itxtb "Level:" Beginner>}}<br>
{{<itxtb "Prerequisites:" "Familiarity with Python*">}}<br>
{{<itxtb "Goal:" "Clarify concepts of machine learning and guide you through the first steps with PyTorch">}}<br>
{{<itxt "Program:" "We will meet during the Zoom sessions">}}<br>
{{<itxt " " "You will go over the material in Readings, Videos, and Practices on your own">}}<br>
{{<itxt " " "Going over the self-directed sections prior to our meetings is necessary to be able to follow">}}<br>
{{<itxtb " " " ">}}<br>
{{<itxtb "Time zone:" "Pacific Daylight Time (UTC-07:00)">}}<br>
{{</i>}}

#+BEGIN_export html
<b>*</b>Those wanting to prepare for this course could take the <a href="/jupyter">Python in Jupyter notebooks</a> course or read the <a href="https://docs.python.org/3/tutorial/">Python</a> and <a href="https://numpy.org/devdocs/user/quickstart.html">NumPy</a> tutorials (PyTorch has <a href="https://pytorch-for-numpy-users.wkentaro.com/">many similarities</a> with NumPy).
#+END_export

*June 8*
{{<zt "9–9:30am">}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-01-intro.html" text="Introduction to the WestGrid Summer School PyTorch course">}}<br>
I will go over the program for this course and we will introduce each other.
{{</zt>}}

{{<reading>}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-02-concepts.html" text="Concepts">}}<br>
{{</reading>}}

{{<video>}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-03-nn.html" text="What are neural networks?">}}<br>
{{</video>}}

{{<practice>}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-04-install.html" text="Installing Python and PyTorch locally">}}<br>
{{</practice>}}

{{<reading>}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-05-cluster.html" text="Running ML jobs on Compute Canada clusters">}}<br>
{{</reading>}}

{{<dt "2–3:30pm">}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-06-debug.html" text="Issues installing PyTorch locally or logging to the training cluster">}}<br>
This session is not part of the actual course. Please only sign up for it if you have followed the instructions on <a href="https://westgrid-ml.netlify.app/school/pt-04-install.html">installing Python and PyTorch</a> but are having issues, or if you are unable to ssh into the training cluster.
{{</dt>}}

{{<practice>}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-07-pytorch.html" text="Introduction to PyTorch">}}<br>
{{</practice>}}

*June 9*
{{<zt "9–10am">}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-08-mlp.html" text="MNIST classification with an MLP">}}<br>
{{</zt>}}

{{<practice>}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-09-cnn.html" text="MNIST classification with a CNN">}}<br>
{{</practice>}}

{{<video>}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-10-tensorboard.html" text="Tracking model performance with TensorBoard">}}<br>
{{</video>}}

{{<reading>}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-11-distributed.html" text="Distributed computing with PyTorch">}}<br>
{{</reading>}}

{{<zt "2–3:30pm">}}
{{<link url="https://westgrid-ml.netlify.app/school/pt-12-tl.html" text="Transfer learning">}}<br>
{{</zt>}}

{{<external>}}
<u>PyTorch documentation:</u>
<br>
<a href="https://pytorch.org/">PyTorch website</a><br>
<a href="https://pytorch.org/docs/stable/index.html">PyTorch documentation</a><br>
<a href="https://pytorch.org/tutorials/">PyTorch tutorials</a><br>
<a href="https://www.fast.ai/">PyTorch online courses</a><br>
<a href="https://github.com/pytorch/examples">PyTorch examples</a><br>
<br>
<u>Getting help with PyTorch:</u>
<br>
<a href="https://discuss.pytorch.org/">PyTorch Discourse forum</a><br>
<br>
<u>Open-access ML preprints:</u>
<br>
<a href="http://arxiv-sanity.com/">Arxiv Sanity Preserver by Andrej Karpathy</a><br>
<a href="https://arxiv.org/list/cs.LG/recent">ML papers in the computer science category on arXiv</a><br>
<a href="https://arxiv.org/list/stat.ML/recent">ML papers in the stats category on arXiv</a><br>
<a href="https://distill.pub/">Distill ML research online journal</a><br>
<br>
<u>Advice and sources for ML:</u>
<br>
<a href="https://web.mit.edu/tslvr/www/lessons_two_years.html">Advice and sources from ML research student</a><br>
<br>
<u>Better Python REPL:</u>
<br>
<a href="https://ipython.org/">IPython</a><br>
<a href="https://www.bpython-interpreter.org/">bpython</a><br>
<a href="https://github.com/prompt-toolkit/ptpython">ptpython</a><br>
<br>
<u>Python IDE:</u>
<br>
<a href="https://wiki.python.org/moin/IntegratedDevelopmentEnvironments">List of IDEs with description</a><br>
<a href="https://en.wikipedia.org/wiki/Comparison_of_integrated_development_environments#Python">Comparison of IDEs</a><br>
<a href="https://github.com/jorgenschaefer/elpy">Emacs Python IDE</a><br>
<a href="https://jupyter.org/">Project Jupyter</a><br>
{{</external>}}
